// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectNhom12.Models;

namespace ProjectNhom12.Migrations
{
    [DbContext(typeof(QLSinhvien_NET1Context))]
    partial class QLSinhvien_NET1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectNhom12.Models.Dangnhap", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnName("username")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int>("Loai")
                        .HasColumnName("loai");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasColumnName("matkhau")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("Username")
                        .HasName("PK__Dangnhap__F3DBC5733C389CD8");

                    b.ToTable("Dangnhap");
                });

            modelBuilder.Entity("ProjectNhom12.Models.Dieukien", b =>
                {
                    b.Property<string>("MaMh")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("MaMhTruoc")
                        .HasColumnName("MaMh_truoc")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("MaMh", "MaMhTruoc")
                        .HasName("pk_Dieukien");

                    b.HasIndex("MaMhTruoc");

                    b.ToTable("Dieukien");
                });

            modelBuilder.Entity("ProjectNhom12.Models.Hocphan", b =>
                {
                    b.Property<string>("MaHp")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Giangvien")
                        .HasMaxLength(100);

                    b.Property<int?>("Hocky");

                    b.Property<string>("MaMh")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("Nam");

                    b.HasKey("MaHp")
                        .HasName("pk_Hocphan");

                    b.HasIndex("MaMh");

                    b.ToTable("Hocphan");
                });

            modelBuilder.Entity("ProjectNhom12.Models.Ketqua", b =>
                {
                    b.Property<string>("MaSv")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("MaHp")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("Diem");

                    b.HasKey("MaSv", "MaHp")
                        .HasName("pk_Ketqua");

                    b.HasIndex("MaHp");

                    b.ToTable("Ketqua");
                });

            modelBuilder.Entity("ProjectNhom12.Models.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("HinhKhoa")
                        .IsUnicode(false);

                    b.Property<int?>("Nam");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("MaKhoa")
                        .HasName("pk_khoa");

                    b.HasIndex("TenKhoa")
                        .IsUnique()
                        .HasName("UQ__Khoa__AAD36158AF51AB08");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("ProjectNhom12.Models.Monhoc", b =>
                {
                    b.Property<string>("MaMh")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("TenMh")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("Tinchi");

                    b.HasKey("MaMh")
                        .HasName("pk_Monhoc");

                    b.HasIndex("MaKhoa");

                    b.ToTable("Monhoc");
                });

            modelBuilder.Entity("ProjectNhom12.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Cmnd")
                        .HasColumnName("CMND")
                        .HasMaxLength(20);

                    b.Property<string>("Diachi")
                        .HasMaxLength(255);

                    b.Property<string>("Gioitinh")
                        .HasMaxLength(4);

                    b.Property<string>("HinhNv")
                        .HasColumnName("HinhNV")
                        .IsUnicode(false);

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Ngayvaolam")
                        .HasColumnType("datetime");

                    b.Property<string>("TenNv")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("MaNv")
                        .HasName("pk_nhanvien");

                    b.HasIndex("MaKhoa");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("ProjectNhom12.Models.Sinhvien", b =>
                {
                    b.Property<string>("MaSv")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Cmnd")
                        .HasColumnName("CMND")
                        .HasMaxLength(20);

                    b.Property<string>("Diachi")
                        .HasMaxLength(255);

                    b.Property<string>("Gioitinh")
                        .HasMaxLength(4);

                    b.Property<string>("HinhSv")
                        .HasColumnName("HinhSV")
                        .IsUnicode(false);

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int?>("Nam");

                    b.Property<string>("TenSv")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("MaSv")
                        .HasName("pk_sinhvien");

                    b.HasIndex("MaKhoa");

                    b.ToTable("Sinhvien");
                });

            modelBuilder.Entity("ProjectNhom12.Models.Dieukien", b =>
                {
                    b.HasOne("ProjectNhom12.Models.Monhoc", "MaMhNavigation")
                        .WithMany("DieukienMaMhNavigation")
                        .HasForeignKey("MaMh")
                        .HasConstraintName("pk_Dieukien_Mh");

                    b.HasOne("ProjectNhom12.Models.Monhoc", "MaMhTruocNavigation")
                        .WithMany("DieukienMaMhTruocNavigation")
                        .HasForeignKey("MaMhTruoc")
                        .HasConstraintName("pk_Dieukien_Mh_truoc");
                });

            modelBuilder.Entity("ProjectNhom12.Models.Hocphan", b =>
                {
                    b.HasOne("ProjectNhom12.Models.Monhoc", "MaMhNavigation")
                        .WithMany("Hocphan")
                        .HasForeignKey("MaMh")
                        .HasConstraintName("fk_Hocphan_k");
                });

            modelBuilder.Entity("ProjectNhom12.Models.Ketqua", b =>
                {
                    b.HasOne("ProjectNhom12.Models.Hocphan", "MaHpNavigation")
                        .WithMany("Ketqua")
                        .HasForeignKey("MaHp")
                        .HasConstraintName("fk_Ketqua_HP");

                    b.HasOne("ProjectNhom12.Models.Sinhvien", "MaSvNavigation")
                        .WithMany("Ketqua")
                        .HasForeignKey("MaSv")
                        .HasConstraintName("fk_Ketqua_SV");
                });

            modelBuilder.Entity("ProjectNhom12.Models.Monhoc", b =>
                {
                    b.HasOne("ProjectNhom12.Models.Khoa", "MaKhoaNavigation")
                        .WithMany("Monhoc")
                        .HasForeignKey("MaKhoa")
                        .HasConstraintName("fk_Monhoc");
                });

            modelBuilder.Entity("ProjectNhom12.Models.NhanVien", b =>
                {
                    b.HasOne("ProjectNhom12.Models.Khoa", "MaKhoaNavigation")
                        .WithMany("NhanVien")
                        .HasForeignKey("MaKhoa")
                        .HasConstraintName("fk_nhanvien_k");

                    b.HasOne("ProjectNhom12.Models.Dangnhap", "MaNvNavigation")
                        .WithOne("NhanVien")
                        .HasForeignKey("ProjectNhom12.Models.NhanVien", "MaNv")
                        .HasConstraintName("fk_nhanvien_dangnhap");
                });

            modelBuilder.Entity("ProjectNhom12.Models.Sinhvien", b =>
                {
                    b.HasOne("ProjectNhom12.Models.Khoa", "MaKhoaNavigation")
                        .WithMany("Sinhvien")
                        .HasForeignKey("MaKhoa")
                        .HasConstraintName("fk_sinhvien_k");

                    b.HasOne("ProjectNhom12.Models.Dangnhap", "MaSvNavigation")
                        .WithOne("Sinhvien")
                        .HasForeignKey("ProjectNhom12.Models.Sinhvien", "MaSv")
                        .HasConstraintName("fk_sinhvien_dangnhap");
                });
#pragma warning restore 612, 618
        }
    }
}
